"use client";

/* eslint-disable react-hooks/set-state-in-effect */
/* eslint-disable react-hooks/preserve-manual-memoization */

import Link from "next/link";
import { useEffect } from "react";

import { useMemo, useState } from "react";

export default function InvestmentAnalysisPage() {

  const [purchasePrice, setPurchasePrice] = useState("");
  const [deposit, setDeposit] = useState("");
  const [loan, setLoan] = useState("");
  const [grossIncome, setGrossIncome] = useState("");
  const [operatingExpenses, setOperatingExpenses] = useState("");
  const [interestExpense, setInterestExpense] = useState("");

  const [unit, setUnit] = useState(10000);

  // 임시저장
  const saveDraft = () => {
    localStorage.setItem(
      "investment-analysis",
      JSON.stringify({
        purchasePrice,
        deposit,
        loan,
        grossIncome,
        operatingExpenses,
        interestExpense,
        unit,
      })
    );
  
    alert("임시저장되었습니다.");
  };

  useEffect(() => {
    const saved = localStorage.getItem(
      "investment-analysis"
    );
  
    if (!saved) return;
  
    const data = JSON.parse(saved);
  
    setPurchasePrice(data.purchasePrice ?? "");
    setDeposit(data.deposit ?? "");
    setLoan(data.loan ?? "");
    setGrossIncome(data.grossIncome ?? "");
    setOperatingExpenses(data.operatingExpenses ?? "");
    setInterestExpense(data.interestExpense ?? "");
    setUnit(data.unit ?? 10000);
  }, []);

  // 오늘 날짜 
  const today = new Date()
  .toISOString()
  .slice(0, 10);

  // txt 추출
  const exportTxt = () => {

    if (!result) {
      alert("먼저 투자 분석을 진행해주세요.");
      return;
    }
  
    const content = `
        부동산 투자 분석 결과
        Investment Analysis Calculator

        작성일: ${today}
        입력 단위: ${unitLabel}
        
        =================================
        
        [입력값]
        입력 단위: ${unitLabel}

        매입가: ${purchasePrice} ${unitLabel}
        보증금 승계: ${deposit} ${unitLabel}
        대출금: ${loan} ${unitLabel}

        연 임대수입: ${grossIncome} ${unitLabel}
        운영비: ${operatingExpenses} ${unitLabel}
        연 이자비용: ${interestExpense} ${unitLabel}
        
        =================================
        
        [분석 결과]
        
        순영업소득 (NOI)
        ${format(result.noi)}
        
        자본환원율 (Cap Rate)
        ${result.capRate.toFixed(2)}%
        
        실투자금 (Equity)
        ${format(result.equity)}
        
        레버리지 (Leverage)
        ${result.leverage.toFixed(2)}x
        
        현금흐름 (Cash Flow)
        ${format(result.cashFlow)}
        
        자기자본수익률 (ROE)
        ${result.roe.toFixed(2)}%
        
        =================================
        
        Generated by AssetPicker
        https://blog.naver.com/assetpicker
        `;
        
        const blob = new Blob(
            [content],
            {
                type: "text/plain;charset=utf-8",
            }
        );
        
        const url = URL.createObjectURL(blob);
        
        const link = document.createElement("a");
        
        link.href = url;
        
        link.download =
            `assetpicker-analysis-${today}.txt`;
        
        document.body.appendChild(link);
        
        link.click();
        
        document.body.removeChild(link);
        
        URL.revokeObjectURL(url);
        };

  // 클립보드 복사
  const copyToClipboard = async () => {

    if (!result) {
      alert("먼저 투자 분석을 진행해주세요.");
      return;
    }
  
    const content = `
        부동산 투자 분석 결과
        
        [입력값]
        
        입력 단위: ${unitLabel}

        매입가: ${purchasePrice} ${unitLabel}
        보증금 승계: ${deposit} ${unitLabel}
        대출금: ${loan} ${unitLabel}

        연 임대수입: ${grossIncome} ${unitLabel}
        운영비: ${operatingExpenses} ${unitLabel}
        연 이자비용: ${interestExpense} ${unitLabel}
        
        
        [분석 결과]
        
        순영업소득 (NOI)
        ${format(result.noi)}
        
        자본환원율 (Cap Rate)
        ${result.capRate.toFixed(2)}%
        
        실투자금 (Equity)
        ${format(result.equity)}
        
        레버리지 (Leverage)
        ${result.leverage.toFixed(2)}x
        
        현금흐름 (Cash Flow)
        ${format(result.cashFlow)}
        
        자기자본수익률 (ROE)
        ${result.roe.toFixed(2)}%
        
        Generated by AssetPicker
    `;
  
    try {
  
      await navigator.clipboard.writeText(content);
  
      alert("분석 결과가 클립보드에 복사되었습니다.");
  
    } catch {
  
      alert("복사에 실패했습니다.");
  
    }
  };     

  // 초기화
  const resetCalculator = () => {

    if (
      !confirm(
        "입력값과 계산 결과를 모두 초기화하시겠습니까?"
      )
    ) {
      return;
    }
  
    setPurchasePrice("");
    setDeposit("");
    setLoan("");
    setGrossIncome("");
    setOperatingExpenses("");
    setInterestExpense("");
  
    localStorage.removeItem(
      "investment-analysis"
    );
  
  };

  // 단위
  const unitLabel =
    unit === 1
        ? "원"
        : unit === 1000
        ? "천원"
        : unit === 10000
        ? "만원"
        : "백만원";

  const result = useMemo(() => {

    const p = Number(purchasePrice) * unit;
    const d = Number(deposit) * unit;
    const l = Number(loan) * unit;

    const gi = Number(grossIncome) * unit;
    const oe = Number(operatingExpenses) * unit;
    const ie = Number(interestExpense) * unit;

    if (!p) return null;

    const noi = gi - oe;
    const capRate = (noi / p) * 100;

    const equity = p - d - l;

    const leverage =
      equity > 0
        ? p / equity
        : 0;

    const cashFlow =
      noi - ie;

    const roe =
      equity > 0
        ? (cashFlow / equity) * 100
        : 0;

    return {
      noi,
      capRate,
      equity,
      leverage,
      cashFlow,
      roe,
    };

  }, [
    purchasePrice,
    deposit,
    loan,
    grossIncome,
    operatingExpenses,
    interestExpense,
    unit,
  ]);

  const format = (n: number) =>
    new Intl.NumberFormat("ko-KR").format(
      Math.round(n)
    );


  return (
    <main className="min-h-screen bg-[#ede4da] text-neutral-900">

        <section className="max-w-5xl mx-auto px-6 py-20">

            <h1 className="text-5xl font-bold">
            부동산 투자 분석 계산기
            </h1>

            <p className="mt-3 text-xl text-neutral-600">
            Investment Analysis Calculator
            </p>

            <p className="mt-6 text-xl text-neutral-700 max-w-3xl">
            수익형 부동산의 주요 투자지표를 한 번에 계산해보세요.
            </p>

            <p className="mt-4 text-sm text-neutral-500">
            AssetPicker · Real Estate Investment Tools
            </p>

        </section>

        <section className="max-w-5xl mx-auto px-6 pb-20">

            <div className="grid md:grid-cols-2 gap-8">

                {/* Inputs */}
                <div className="border border-black/10 rounded-2xl p-6 bg-white/30">

                <h2 className="text-2xl font-semibold mb-6">
                    입력값 (Inputs)
                </h2>

                {/* 단위 선택 */}
                <div className="mb-6">

                    <div className="flex items-center gap-2 mb-2">

                    <span className="text-sm font-medium">
                        입력 단위
                    </span>

                    <span className="text-xs text-neutral-500">
                        Input Unit
                    </span>

                    </div>

                    <select
                    value={unit}
                    onChange={(e) => setUnit(Number(e.target.value))}
                    className="w-full rounded-xl border border-black/10 p-3"
                    >
                    <option value={1}>원</option>
                    <option value={1000}>천원</option>
                    <option value={10000}>만원</option>
                    <option value={1000000}>백만원</option>
                    </select>

                </div>
                {/* 입력값들 */}

                <div className="space-y-4">

                <div>
                    <div className="flex items-center gap-2 mb-2">

                        <span className="text-sm font-medium">
                        매입가
                        </span>

                        <span className="text-xs text-neutral-500">
                        Purchase Price
                        </span>

                    </div>

                    <input
                        type="number"
                        value={purchasePrice}
                        onChange={(e) => setPurchasePrice(e.target.value)}
                        className="w-full rounded-xl border border-black/10 p-3 text-right"
                    />
                </div>

                <div>
                    <div className="flex items-center gap-2 mb-2">

                        <span className="text-sm font-medium">
                        보증금 승계
                        </span>

                        <span className="text-xs text-neutral-500">
                        Deposit Assumption
                        </span>

                    </div>

                    <input
                        type="number"
                        value={deposit}
                        onChange={(e) => setDeposit(e.target.value)}
                        className="w-full rounded-xl border border-black/10 p-3 text-right"
                    />
                </div>

                <div>
                    <div className="flex items-center gap-2 mb-2">

                        <span className="text-sm font-medium">
                        대출금
                        </span>

                        <span className="text-xs text-neutral-500">
                        Loan Amount
                        </span>

                    </div>

                    <input
                        type="number"
                        value={loan}
                        onChange={(e) => setLoan(e.target.value)}
                        className="w-full rounded-xl border border-black/10 p-3 text-right"
                    />
                </div>

                <div>
                    <div className="flex items-baseline gap-2 mb-2">

                        <span className="text-sm font-medium">
                        연 임대수입
                        </span>

                        <span className="text-xs text-neutral-500">
                        Annual Gross Income
                        </span>

                    </div>

                    <input
                        type="number"
                        value={grossIncome}
                        onChange={(e) => setGrossIncome(e.target.value)}
                        className="w-full rounded-xl border border-black/10 p-3 text-right"
                    />
                </div>

                <div>
                    <div className="flex items-center gap-2 mb-2">

                        <span className="text-sm font-medium">
                        운영비
                        </span>

                        <span className="text-xs text-neutral-500">
                        Operating Expenses
                        </span>

                    </div>

                    <input
                        type="number"
                        value={operatingExpenses}
                        onChange={(e)=>setOperatingExpenses(e.target.value)}
                        className="w-full rounded-xl border border-black/10 p-3 text-right"
                    />
                </div>

                <div>
                    <div className="flex items-center gap-2 mb-2">

                        <span className="text-sm font-medium">
                        연 이자비용
                        </span>

                        <span className="text-xs text-neutral-500">
                        Annual Interest Expense
                        </span>

                    </div>

                    <input
                        type="number"
                        value={interestExpense}
                        onChange={(e)=>setInterestExpense(e.target.value)}
                        className="w-full rounded-xl border border-black/10 p-3 text-right"
                    />
                </div>
            </div>

        </div>

                {/* Results */}
                <div className="border border-black/10 rounded-2xl p-6 bg-white/30">

                    <div className="flex items-center justify-between mb-6">

                        <h2 className="text-2xl font-semibold">
                            분석 결과 (Results)
                        </h2>

                        <div className="flex items-center gap-2">

                            <button
                                onClick={saveDraft}
                                className="px-3 py-2 rounded-lg border border-black/10 bg-white hover:bg-white/70"
                            >
                                임시저장
                            </button>
                            <button
                                onClick={copyToClipboard}
                                className="px-3 py-2 rounded-lg border border-black/10 bg-white hover:bg-white/70"
                            >
                                복사
                            </button>

                            <button
                                onClick={exportTxt}
                                className="px-3 py-2 rounded-lg bg-black text-white hover:opacity-80 transition"
                                >
                                TXT 추출
                            </button>

                            <button
                                onClick={resetCalculator}
                                className="px-3 py-2 rounded-lg border border-black/10 bg-white hover:bg-white/70"
                            >
                                초기화
                            </button>

                        </div>

                    </div>

                {result ? (

                    <div className="space-y-4">

                    <div>
                        <div className="text-sm text-neutral-500">
                        순영업소득 (NOI)
                        </div>

                        <div className="text-2xl font-bold">
                        ₩{format(result.noi)}
                        </div>
                    </div>

                    <div>
                        <div className="text-sm text-neutral-500">
                        자본환원율 (Cap Rate)
                        </div>

                        <div className="text-2xl font-bold">
                        {result.capRate.toFixed(2)}%
                        </div>
                    </div>

                    <div>
                        <div className="text-sm text-neutral-500">
                        실투자금 (Equity)
                        </div>

                        <div className="text-2xl font-bold">
                        ₩{format(result.equity)}
                        </div>
                    </div>

                    <div>
                        <div className="text-sm text-neutral-500">
                        레버리지 (Leverage)
                        </div>

                        <div className="text-2xl font-bold">
                        {result.leverage.toFixed(2)}x
                        </div>
                    </div>

                    <div>
                        <div className="text-sm text-neutral-500">
                        현금흐름 (Cash Flow)
                        </div>

                        <div className="text-2xl font-bold">
                        ₩{format(result.cashFlow)}
                        </div>
                    </div>

                    <div>
                        <div className="text-sm text-neutral-500">
                        자기자본수익률 (ROE)
                        </div>

                        <div className="text-2xl font-bold">
                        {result.roe.toFixed(2)}%
                        </div>
                    </div>

                    </div>

                ) : (

                    <p className="text-neutral-500">
                    입력값을 입력하면 분석 결과가 표시됩니다.
                    </p>

                )}

                </div>

            </div>

        </section>
                    
        {result && (

        <section className="max-w-5xl mx-auto px-6 pb-20">

            {/* 계산 과정 */}

            <div className="border border-black/10 rounded-2xl p-6 bg-white/20">

            <h2 className="text-2xl font-semibold mb-6">
                    계산 과정 (Analysis Breakdown)
                </h2>

                <div className="grid md:grid-cols-2 gap-4">

                <div>
                <div className="font-medium">
                    순영업소득 (NOI)
                </div>

                <div className="text-neutral-600">
                    {format(Number(grossIncome))}
                    {" - "}
                    {format(Number(operatingExpenses))}
                    {" = "}
                    {format(result.noi)}
                </div>
                </div>

                <div>
                <div className="font-medium">
                    자본환원율 (Cap Rate)
                </div>

                <div className="text-neutral-600">
                    {format(result.noi)}
                    {" ÷ "}
                    {format(Number(purchasePrice))}
                    {" × 100"}
                    {" = "}
                    {result.capRate.toFixed(2)}%
                </div>
                </div>

                <div>
                <div className="font-medium">
                    실투자금 (Equity)
                </div>

                <div className="text-neutral-600">
                    {format(Number(purchasePrice))}
                    {" - "}
                    {format(Number(deposit))}
                    {" - "}
                    {format(Number(loan))}
                    {" = "}
                    {format(result.equity)}
                </div>
                </div>

                <div>
                <div className="font-medium">
                    현금흐름 (Cash Flow)
                </div>

                <div className="text-neutral-600">
                    {format(result.noi)}
                    {" - "}
                    {format(Number(interestExpense))}
                    {" = "}
                    {format(result.cashFlow)}
                </div>
                </div>

                <div>
                <div className="font-medium">
                    자기자본수익률 (ROE)
                </div>

                <div className="text-neutral-600">
                    {format(result.cashFlow)}
                    {" ÷ "}
                    {format(result.equity)}
                    {" × 100"}
                    {" = "}
                    {result.roe.toFixed(2)}%
                </div>
                </div>
                </div>

            </div>

        </section>

        )}
        <section className="max-w-5xl mx-auto px-6 pb-20">
            <div className= "mt-10">
                <h2 className="text-2xl font-semibold mb-6">
                    관련 계산기 (Related Calculators)
                </h2>

                <div className="grid md:grid-cols-2 gap-4">

                    <Link
                    href="/products/real-estate-toolkit/noi"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="border border-black/10 rounded-xl p-4 bg-white/40 hover:bg-white/60 transition"
                    >
                    <div className="font-semibold">
                        순영업소득 (NOI)
                    </div>

                    <div className="text-sm text-neutral-600 mt-1">
                        NOI 계산기로 이동
                    </div>
                    </Link>

                    <Link
                    href="/products/real-estate-toolkit/cap-rate"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="border border-black/10 rounded-xl p-4 bg-white/40 hover:bg-white/60 transition"
                    >
                    <div className="font-semibold">
                        자본환원율 (Cap Rate)
                    </div>

                    <div className="text-sm text-neutral-600 mt-1">
                        Cap Rate 계산기로 이동
                    </div>
                    </Link>

                    <Link
                    href="/products/real-estate-toolkit/equity"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="border border-black/10 rounded-xl p-4 bg-white/40 hover:bg-white/60 transition"
                    >
                    <div className="font-semibold">
                        실투자금 (Equity)
                    </div>

                    <div className="text-sm text-neutral-600 mt-1">
                        Equity 계산기로 이동
                    </div>
                    </Link>

                    <Link
                    href="/products/real-estate-toolkit/leverage"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="border border-black/10 rounded-xl p-4 bg-white/40 hover:bg-white/60 transition"
                    >
                    <div className="font-semibold">
                        레버리지 (Leverage)
                    </div>

                    <div className="text-sm text-neutral-600 mt-1">
                        Leverage 계산기로 이동
                    </div>
                    </Link>

                    <Link
                    href="/products/real-estate-toolkit/roe"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="border border-black/10 rounded-xl p-4 bg-white/40 hover:bg-white/60 transition"
                    >
                    <div className="font-semibold">
                        자기자본수익률 (ROE)
                    </div>

                    <div className="text-sm text-neutral-600 mt-1">
                        ROE 계산기로 이동
                    </div>
                    </Link>

                    </div>
                </div>   

                {/* AssetPicker */}

                <div className="mt-10 border border-black/10 rounded-2xl p-6 bg-white/20">

                    <h2 className="text-2xl font-semibold">
                    AssetPicker
                    </h2>

                    <p className="mt-3 text-neutral-600">
                    부동산 투자 사례, 시장 분석 및 수익률 분석 콘텐츠를 확인해보세요.
                    </p>

                    <a
                    href="https://blog.naver.com/assetpicker"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-block mt-4 underline"
                    >
                    AssetPicker 방문하기 →
                    </a>

                </div>    

            </section>
            <section className="max-w-5xl mx-auto px-6 pb-20">

<div className="border-t border-black/10 pt-8">

  <h2 className="text-lg font-medium text-neutral-700">
    모아보기
    <span className="ml-2 text-sm text-neutral-500">
      Related Calculators
    </span>
  </h2>

  <div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm">

    <Link
      href="/products/real-estate-toolkit/noi"
      target="_blank"
      rel="noopener noreferrer"
      className="hover:underline"
    >
      순영업소득 (NOI)
    </Link>

    <Link
      href="/products/real-estate-toolkit/cap-rate"
      target="_blank"
      rel="noopener noreferrer"
      className="hover:underline"
    >
      자본환원율 (Cap Rate)
    </Link>

    <Link
      href="/products/real-estate-toolkit/equity"
      target="_blank"
      rel="noopener noreferrer"
      className="hover:underline"
    >
      실투자금 (Equity)
    </Link>

    <Link
      href="/products/real-estate-toolkit/leverage"
      target="_blank"
      rel="noopener noreferrer"
      className="hover:underline"
    >
      레버리지 (Leverage)
    </Link>

    <Link
      href="/products/real-estate-toolkit/roe"
      target="_blank"
      rel="noopener noreferrer"
      className="hover:underline"
    >
      자기자본수익률 (ROE)
    </Link>

    <Link
      href="/products/real-estate-toolkit/loan-calculator"
      target="_blank"
      rel="noopener noreferrer"
      className="hover:underline"
    >
      대출상환 (Loan)
    </Link>

  </div>

  <div className="mt-8 text-sm text-neutral-600">

    <span className="font-medium">
      AssetPicker
    </span>

    <a
      href="https://blog.naver.com/assetpicker"
      target="_blank"
      rel="noopener noreferrer"
      className="ml-3 underline"
    >
      방문하기 →
    </a>

  </div>

</div>

</section>
    </main>
  );
}